### ISSUE TITLE
Ensure all component fields can be changed at runtime and can be set via UnityEvents

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Zinnia.Unity#209]
Because a public field cannot be set by a UnityEvent this means that components cannot use public fields for data input otherwise they require scripts to set field data.

A property can be set by a UnityEvent by anything that extends from UnityEngine.Object can't be set to null via a property unity event.

This means any field that wants a value to be updatable and also potentially requires any configuration to run when the value is changed needs to be backed by the following pattern

```
#region MyType
[Tooltip("Documentation here"), SerializeField]
private Type myType;
/// <summary>
/// Documentation here
/// </summary>
public virtual Type MyType
{
  get { return myType;}
  set
  {
    myType = value;
    ....Any extra setup
  }
}
/// <summary>
/// Clears MyType
/// </summary>
public virtual void ClearMyType()
{
  MyType = null;  
}
#endregion
```

This will allow a private field to store the data, a public Property to allow setting via a UnityEvent and a method for setting the field to `null`

**Comment by thestonefox** [comment]
I propose rather than one big commit, many smaller commits that focus on each namespace/prefab at a time

**Comment by bddckr** [comment]
We discussed the idea of a wrapper of the actual value to ensure we aren't forced to write the same huge blob of code for each field:

* ScriptableObjects don't work as they can't reference scene entities.
* MonoBehaviours work but pollute everything (one could hide them -> bad magic) or offer nice editor tooling to create them inline by putting them into a fixed place and then offer tooling to view and find references in the scene etc. This has the big downside of us having to maintain this but is the cleanest solution as we're building upon, rather than get hacks into things we don't control.
* Extending and customizing the UnityEvent inspector would probably work but is a lot of work and fragile. Maintaining this can become even impossible depending on the changes Unity does in the future.
* Writing our own UnityEvent replacement to get full control over it means us creating the biggest solution of this all - one where we don't just need good editor tooling, it also means getting generic serialization right as well as doing all this little things Unity currently offers (e.g. understanding you just renamed a type and thus the serialized event listener didn't really change).

**Comment by bddckr** [comment]
Something the initial message's solution is missing is an `OnValidate` implementation that triggers the setter logic of all properties.

**Comment by thestonefox** [comment]
A more complete use case:

```
Primitive:
* ability to store data on a component [private field + public Property]
* ability to get data from a component [private field + public Property]
* ability to set data on a component [private field + public Property]
* changing data value may require in reconfiguring internal state [private field + public Property + OnValidate]
* ability to set data via a UnityEvent [private field + public Property]
* ability to null data via a UnityEvent [private field + public Property]

Object:
* ability to store data on a component [private field + public Property]
* ability to get data from a component [private field + public Property]
* ability to set data on a component [private field + public Property]
* changing data value may require in reconfiguring internal state [private field + public Property + OnValidate]
* ability to set data via a UnityEvent [private field + public Property]
* ability to null data via a UnityEvent [private field + public Clear Method]

Collection:
* ability to store data on a component [private field + public Property]
* ability to get data from a component [private field + public Property]
* ability to set data on a component [private field + public Property]
* changing data value may require in reconfiguring internal state [private field + public Property + ObservableCollection + OnValidate]
* ability to set data via a UnityEvent [private field + public Property]
* ability to null data via a UnityEvent [private field + public Clear Method]

Sub Class:
* Sub class always extends MonoBehaviour and only contains public fields and only data container
* ability to store data on a component [private field + public Property]
* ability to get data from a component [private field + public Property]
* ability to set data on a component [private field + public Property]
* changing data value may require in reconfiguring internal state [private field + public Property + OnValidate]
* ability to set data via a UnityEvent [private field + public Property]
* ability to null data via a UnityEvent [private field + public Clear Method (clears individual sub class elements, doesn't null containing param]
```

**Comment by thestonefox** [comment]
Potentially fixed with: https://github.com/ExtendRealityLtd/VRTK.Unity.Core/issues/210

**Comment by thestonefox** [comment]
Requires #210 as this ticket isn't actually the code weaving task. This ticket is updating all of the code with the new tags introduced by the code weaving task

**Comment by thestonefox** [comment]
We're done with this now too, right?

**Comment by bddckr** [comment]
Yes! This is resolved by a big mixture of Malimbe features, using Malimbe here in Zinnia and making some previously nested types MonoBehaviours. All done!
