### ISSUE TITLE
IProcessable that wraps up events

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#445]
I come up with a wrapper when Process() it will invoke events.
![image](https://user-images.githubusercontent.com/22952143/67419624-a24e0b00-f5ff-11e9-98e8-c00f39a2acd6.png)

this one is for no arguments, probably naming should be EmptyEventProxyProcessable
would it be a candidate to add to zinnia? as well as others such as FloatEventProxyProcessable

**Comment by thestonefox** [comment]
so what does this do? when a momentprocess has finished processing it emits an event to say the moment has done processing?

**Comment by thestonefox** [comment]
or is this something that will call an event every loop of the given moment?

**Comment by fight4dream** [comment]
the later. to call an event every loop of the given moment

**Comment by thestonefox** [comment]
i think that's pretty useful. I think that may actually solve a problem with the teleport/surface locator issue.

So you can basically have something at the end of a MomentProcessor which is an event that you want to do something.

You can then do kinda like "wait till end of frame" type stuff with those events.

I don't think this is a Proxy though

it's more like `EmptyEventProcess : EventProcessable`

@bddckr any thoughts on this?

**Comment by bddckr** [comment]
So you basically get to call methods from the inspector as part of a specific moment?

Sure I like it. This basically means the process abstraction goes all the way and allows being explicit about a lot of things (as they can all be nested and chained together), right there without resorting to code.

In terms of implementation details: I'd expect to have the following classes:
* `abstract` base class `EventProcess` (or remove if the next two don't share anything)
* `abstract` intermediate base class `EventProcess<TValue>`
* specific implementation `EmptyEventProcessable : EventProcess` for calling empty methods

---

A few things that reduce the usefulness though:
1. No support for calling any method without having a specific `EventProcessable<TValue>` subclass created in advance, that matches the signature of the method to call.
2. Passing on multiple arguments to a method (i.e. calling any method that takes more than one argument) means one can't even just inherit from the `TValue` one as one needs _multiple_ values.
3. Arguments passed can only be constant. Unity doesn't support a lot of types here at all, even a `Vector3` can't be used.

**My current opinion, due to these, is to only offer the `EmptyEventProcess` class.** Instead of creating a specific subclass for all the calling needs us and users would be better off just writing the method call in code already. Additionally the in-code solution doesn't have issue 3 - one can retrieve and propagate values as needed. Unity events aren't a replacement for visual scripting after all.

If this would be the outcome I suggest to not introduce unnecessary complexity via additional base class(es) just yet - literally just offer the `EmptyEventProcess`.

**Comment by thestonefox** [comment]
I may be missing the point on the different Unity event types.

But isn't this just a case of you can have a Process that simply emits an event every frame

So you have `EventProcess`

and all it does is emits an empty event

Now in that empty event you can call whatever method you want, and Unity events let you specify a certain number of types of a single parameter for the method you're calling.

At any point you want to call something more complex I would say at that point you want to proxy through an intermediate script that does the extra parameter set up. Rather than having many different EventProcesses

**Comment by fight4dream** [comment]
Oh indeed. no use case in my head either to call fixed argument every moment. 
So i will just rename the class and that’s good?

**Comment by thestonefox** [comment]
Yeah I think just `EventProcess` that simply just implements `Process` and calls an empty event each moment, that's a good inclusion imho

**Comment by bddckr** [comment]
Simple process that raises an event each loop to then do whatever in the inspector with it :+1:

**Comment by fight4dream** [comment]
Side track: what is the “wait for end of frame” stuff and how you would use this here? Or sounds like you want a processor moment of “end of frame”

**Comment by thestonefox** [comment]
no, i meant more of you can set up something to turn off a GameObject so in essence no processing happens, then the moment processor runs and does all it's processing, then the last process is an event which turns the disabled thing back on, therefore next time the moment processor runs it will be enabled to process.

I have this very issue with the SnapToFloor stuff, I think this solution may fix the problem
