### ISSUE TITLE
CollisionTracker either too many disabled observer added or none

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Zinnia.Unity#464]
Problem 1:

1. Use CollisionTracker, set States To Process = "Enter" only

2. Collide repeatedly with a target, the disabled observer is added for each Enter and not being removed

Problem 2:

1. Use CollisionTracker, set State To Process = "Exit" only

2. Collide with a target, notice that no disabled observer is added.

3. Disable either of the tracker or target. no Exit event is emitted

**Comment by fight4dream** [comment]
I agree. yes and yes

**Comment by thestonefox** [comment]
Ok what about this stupid edge case:

You're not tracking exit:

* the thing enters
* whilst it is in the enter state you change the thing to track exit
* You now disable the component

You won't get an exit state because the helper component was never added.

So maybe need to do some tracking of the property value as well.

**Comment by fight4dream** [comment]
A naive approach would be to add/remove helper component disregard the state settings.

The state setting would then only control the event emit

**Comment by thestonefox** [comment]
Yeah that may actually be easier. So you *always* add the observer component but you just ignore the internal state.
