### ISSUE TITLE
Wrong velocity calculation in RigidbodyAngularVelocity follow modifier

### ISSUE THREAD

**Issue by JGroxz** [ExtendRealityLtd/Zinnia.Unity#518]
### Environment

* Zinnia version: 1.25.0
* Unity version: 2018.3+
* 3rd party dependencies: None

### Steps to reproduce

1. Create an empty Unity project with Zinnia package added to it.
2. Create a new empty scene.
3. Setup objects:
  3.1. Create a cube, name it "Follower Cube". Scale to (0.1; 1; 10).
  3.2. Create another cube, "Target Cube". Scale to (0.1; 1; 10).
  3.3. Create a new Material, paint it bright red and apply it to the "Follower". It will help distinguish the objects visually.
  3.4. Add non-kinematic Rigidbody to the "Follower Cube".
  3.5. Remove colliders form both cubes.
4. Create script to rotate the "Target Cube" in FixedUpdate:
  4.1. Create a new script, "RotateInFixedUpdate" (sample code below). Make it rotate a transform in FixedUpdate:
  4.2. Add this script component to "Target Cube".
6. Setup Zinnia's "ObjectFollower" script.
	6.1. Put "Target Cube" to "Sources" list.
	6.2. Put "Follower Cube" to "Targets" list.
	6.3. Use "Rigidbody Angular Velocity" as Rotation Modifier.
	6.4. Use any modifiers for position and scale (i.e. "Transform Position", "Transform Scale").
7. In "Project Settings -> Time", reduce physics timestep to 0.05 (20 FPS). This will make it easier to observe the effect.
7. Run the scene.

Code for "RotateInFixedUpdate":
```c#
using UnityEngine;

public class RotateInFixedUpdate : MonoBehaviour
{
    public float rotationSpeed = 60f;

    private void FixedUpdate()
    {
        var rotationDelta = new Vector3(0f,rotationSpeed,0f) * Time.deltaTime;
        transform.Rotate(rotationDelta);
    }
}
```

### Expected behavior

"Follower" follows the "Target" rotation smoothly (with small offset due to FixedUpdate).

### Current behavior

"Follower" jumps around the "Target" orientation each frame, but fails to align with it.

### Possible cause

Current implementation of _RigidbodyAngularVelocity_ follow modifier script calculates angle difference in degrees, clamps it and applies it directly to the velocity of follower Rigidbody (lines 48-61 of the original script):
```c#
Quaternion rotationDelta = source.transform.rotation * Quaternion.Inverse(offset != null ? offset.transform.rotation : target.transform.rotation);

rotationDelta.ToAngleAxis(out float angle, out Vector3 axis);
angle = angle.GetSignedDegree();

if (!angle.ApproxEquals(0))
{
    Vector3 angularTarget = angle * axis;
    Vector3 calculatedAngularVelocity = Vector3.MoveTowards(cachedTargetRigidbody.angularVelocity, angularTarget, MaxDistanceDelta);
    if (float.IsPositiveInfinity(AngularVelocityLimit) || calculatedAngularVelocity.sqrMagnitude < AngularVelocityLimit)
    {
        cachedTargetRigidbody.angularVelocity = calculatedAngularVelocity;
    }
}
```
There are 2 problems with this:
1. "angle" is not converted to radians. [_Rigidbody.angularVelocity_](https://docs.unity3d.com/ScriptReference/Rigidbody-angularVelocity.html) accepts radians, _not_ degrees.
2. "angle" is not divided by _Time.deltaTime_ before being applied as a velocity.

### Proposed solution

Convert angle to radians and divide it by deltaTime before applying it as angular velocity.
This can be done by changing line 51 of current _RigidbodyAngularVelocity_ script to:
```c#
angle = angle * Mathf.Deg2Rad / Time.deltaTime;
```

**Comment by thestonefox** [comment]
I think you may have misunderstood the Source/Target

The Source is the source of movement/orientation, the Target is the object to apply the data to.

If you get a Target to follow a Source and then try and rotate the Target then this will not work because the Target rotation is attempting to always match the Source.

In this above example you are applying a rotation script to the Target, but that's not going to work because the Target can only rotate based on what the Source is doing.

**Comment by thestonefox** [comment]
Oh wait, I see you then put the TargetSources in the Sources

**Comment by thestonefox** [comment]
I'm happy with the fix you've suggested, do you want to do a Pull Request for it or want me to do it and credit you in the commit?

**Comment by JGroxz** [comment]
I will be glad if you do a commit and just credit me there. Thank you!

**Comment by thestonefox** [comment]
Fixed in https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/519

**Comment by thestonefox** [comment]
This solution has caused breaking changes in how the rigidbody grab mechanic works so the solution needs reworking

**Comment by SmartCarrion** [comment]
Shouldn't this all be done in quaternions with no vector3 conversions? That could be cause of many of the rotation following issues.

**Comment by thestonefox** [comment]
angular velocity is a vector3 not a quaternion

**Comment by JGroxz** [comment]
Though description in the issue mentioned seems different, there is one problem I had with physical follow.
When correctly applying rotational velocity (after this fix), some objects can visibly lag behind the rotation of the source (Interactor), leading to difference in rotation. This happens because Unity has angular velocity limit set to 7 rad/s by default in Physics settings. This is much slower than the typical user's hand can rotate and results in weird behavior. Increasing this value to 50+ solves the delay issue.
I can't find it right now, but there is a Unity forum thread where one of the devs admitted that this value is from old days of PhysX (say 10+ years ago) and they left it so low for backwards compatibility. It can be safely increased.

**Comment by thestonefox** [comment]
the thing you're talking about is already applied in the interactable prefab. It's the MaxAngularVelocity by default is randomly set to 7 by unity, but it is forced to be infinity to prevent such issues.

**Comment by fight4dream** [comment]
Hi all, I followed @JGroxz 's setup but use a Mutator.RigidbodyFollower instead of a regular Mutator.ObjectFollower because it is meant to use with a rigidbody (and it thus uses the RigidbodyAngularVelocity).
So far so good.
![image](https://user-images.githubusercontent.com/22952143/100643130-a1e08180-3374-11eb-85b7-1578d8ab15b0.png)
I made the source object rotate very fast, so the target lags behind a bit is reasonable.

Base on this, for @SmartCarrion problem, I tested with a TargetOffset (because a precision grab / orientation handle is a kind of target offset).
![image](https://user-images.githubusercontent.com/22952143/100643964-ac4f4b00-3375-11eb-8e5a-242bc7f74b8b.png)

![image](https://user-images.githubusercontent.com/22952143/100644158-e9b3d880-3375-11eb-9a4c-ad8f9b21ab90.png)
This is the failed situtaion. (wobble, erratic rotation)

![image](https://user-images.githubusercontent.com/22952143/100644341-28e22980-3376-11eb-917f-d8267ad02c93.png)
This is the situation if I lowered the rotation speed. (the target offset is at its correct location and the rotation is followed)

### Insight
If we precision grab a thing and we attempt to rotate it, we would expect the rotation pivot is at the grab point. In fact, the rigidbody.angularVelocity is rotate around its centerOfMass.

### Suggested solution
![image](https://user-images.githubusercontent.com/22952143/100643439-fe43a100-3374-11eb-95c6-326c319337aa.png)
Set the centerOfMass to the Target offset (grabbed location).

![image](https://user-images.githubusercontent.com/22952143/100645284-698e7280-3377-11eb-8263-ff9ff54f8ce3.png)
correct result even with fast rotation

**Comment by thestonefox** [comment]
The CentreOfMass does aid the issue with the rotation follow (it isn't perfect still) but it doesn't fix the interactable precision grab of a rigidbody follow. It still has crazy rotation

![grabbug](https://user-images.githubusercontent.com/1029673/101356028-61f72e00-388f-11eb-9a4d-319789d94bda.gif)

**Comment by thestonefox** [comment]
I'm reopening this issue and closing the other issues as i think this is the core problem

**Comment by thestonefox** [comment]
Right now, all I can think of to fix this is an option that lets you choose how to handle the angle calculation.

**Comment by fight4dream** [comment]
> The CentreOfMass does aid the issue with the rotation follow (it isn't perfect still) but it doesn't fix the interactable precision grab of a rigidbody follow. It still has crazy rotation
> 
> ![grabbug](https://user-images.githubusercontent.com/1029673/101356028-61f72e00-388f-11eb-9a4d-319789d94bda.gif)

Could you provide the interactable settings please?

**Comment by thestonefox** [comment]
just setting to Follow Rigidbody and Precision Grab

**Comment by thestonefox** [comment]
Would the issue here be that previously when using degrees it was using `Signed` degrees (-180 to 180) so when working out the calculated velocity it would know to move the correct direction.

But now with radians, we're always using positive radians.

Debug logging the angle with radians shows sometimes the value goes very high into the 300s maybe when the problem occurs.

So is this an issue with radians not being signed perhaps?

**Comment by thestonefox** [comment]
Yup, this is the problem. I've added a `GetSignedRadian` method and turn the radians into signed radians and it fixes the problem with grabbing, and doesn't introduce a problem with this original ticket

**Comment by fight4dream** [comment]
you can also change the original signed angle before converting to radian,
also the 'deltaTime' needs to be time step proofed.

```
rotationDelta.ToAngleAxis(out float angle, out Vector3 axis);
angle = angle.GetSignedAngle();
float deltaTime = Time.inFixedTimeStep? Time.fixedDeltaTime : Time.deltaTime;
angle = angle * Mathf.Deg2Rad / deltaTime;
```

**Comment by thestonefox** [comment]
yeah i prefer that, then we don't need a GetRadianAngle helper

**Comment by thestonefox** [comment]
i'll do a PR soon, do you wanna update your PR and remove the commit to do with this stuff as mine will include it all?

**Comment by fight4dream** [comment]
i can update my PR

**Comment by thestonefox** [comment]
even though i've converted everything to radians and on the surface it "works", the interactable still works better if using `SignedDegrees` when working in radians, you get an ever so slight wobble, so I propose keeping all the radian stuff in, but having an option to still calculate in degrees as a legacy feature as it works best for interactable grabbing

**Comment by thestonefox** [comment]
PR with fix for this (and fix for the issue caused in the interactable) 

https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/521
