### ISSUE TITLE
Add documentation / prefab on how to properly use PlatformDeviceAssociation with object state switcher

### ISSUE THREAD

**Issue by studentutu** [ExtendRealityLtd/Zinnia.Unity#522]
It would be nice to have some sort of prefab on how to auto-enable target SDK rig (depending on the currently found HMD). It is even better if you could put a prefab for Oculus in there.

Copy from https://github.com/ExtendRealityLtd/Tilia.Utilities.ObjectStateSwitcher.Unity/issues/34

**Comment by studentutu** [comment]
PlatformDeviceAssociation  Changed to https://github.com/ExtendRealityLtd/Zinnia.Unity/issues/557

**Comment by thestonefox** [comment]
From discord chat:
ok so there are 3 new `PattermMatchers`

* `XRSettingsPatternMatcher`
* `XRDevicePatternMatcher`
* `SystemInfoPatternMatcher`

each one works very simply

you select a source of a string of what you want to match on, and a regular expression to match with
so for example

XRDevicePatternMatcher you can select the Property Source as Model
which should report the model of the headset
so in the `Pattern` you could put like Oculus

and then when that `PatternMatcher` has the `DoMatch` method run on it, if you're using an Oculus headset then the `Model` will report as `Oculus` and the `PatternMatcher` will match as true

so now you can use that with with a `PatternMatcherRule`

where one or many patterns can belong to that rule. so if all of the given patterns match then the rule will be true

now... you can use that `Rule` with the new `Rule Association` component

which is a collection of gameobjects to turn on if the rule is true, or turn off if the rule is false
so now you can have a pattern that says `if model is oculus` -> `then my rule will be true if i'm using an oculus` -> `therefore turn on these gameobjects because i'm on oculus`

you can then run this into the `GameObjects Association Activator`

which will turn them on when the scene is enabled

![image](https://user-images.githubusercontent.com/1029673/152198349-57933a94-bd85-40b3-81ac-cf62e3eb1b37.png)


XRDevicePatternMatcher looking for the string `Oculus*` (anything that starts with Oculus)

then we create a rule based on that matched pattern (in the PatternMatcherRule). this says if the rule we give it is true then the rule is true.

then we add a RuleAssociation, that says if the given rule is true then we're going to assume the list of gameobjects should be active

Then finally we use a GameObjectsAsscciationActivator to say go through the rule associations and toggle on/off their gameobject collections if their rules are true/false
this is the pain and joy of v4. its very powerful, but that inherently makes it more complicated
making this super easy and dumbed down would make it a complete pain to support other devices or use cases
right now with this system you could do things like

`if oculus then make the teleport pointer blue, or if htc vice then make the teleport pointer green` etc

**Comment by fight4dream** [comment]
1. Windows -> Zinnia -> Observable List Component Generator

Choose `Game Objects Association Activator` then press `Generate Component`
![image](https://user-images.githubusercontent.com/22952143/186629097-6a914c13-8d57-4b5a-9c0c-bd3ca3f49d70.png)

2. Choose `Rule Association`, type in `Oculus Association` then press `Generate Component`
![image](https://user-images.githubusercontent.com/22952143/186630061-0eec64ac-6ef2-4fc0-857c-8984d925f771.png)

3. Drag the desired game objects associated with oculus (e.g. CameraRig.OculusIntegration) into the `Game Objects` array of rule association
![image](https://user-images.githubusercontent.com/22952143/186631390-dd5022d2-b793-4717-9b61-5bafcbae9ef8.png)

4. Choose `Pattern Rule Matcher`, type in `Detect Oculus` then press `Generate Component`
![image](https://user-images.githubusercontent.com/22952143/186631878-2d7a9816-3ba7-4f2a-a850-39b0bc6077e0.png)

5. Add component `XRDevicePatternMatcher`, set Pattern=`Oculus*`, PropertySource=`Model`, DeviceSource=`Head`
Drag the component into the `Patterns` array of the pattern rule matcher
![image](https://user-images.githubusercontent.com/22952143/186632215-0c52096e-0c39-4aad-835a-508519741a2f.png)

6. Drag this rule into the rule association
![image](https://user-images.githubusercontent.com/22952143/186632895-c398f81a-a47a-41a6-ac30-4d49310a59fc.png)

7. Drag the rule association into the game objects association activator
![image](https://user-images.githubusercontent.com/22952143/186633183-207f434d-8d4d-4861-a3ca-944a122642fe.png)

When play, if the rule detects oculus, it will activate the CameraRig.OculusIntegration.

Repeat steps 2-7 to detect other things
