### ISSUE TITLE
FloatToBoolean Positive Bounds cannot be the same for an equality check

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Zinnia.Unity#566]
If you use a FloatToBoolean and set the bounds min to 5 and the max to 5, then if the given float is 5 then it should be a true output boolean

**Comment by fight4dream** [comment]
from FloatToBoolean.cs
```
        protected override bool Process(float input)
        {
            return PositiveBounds.Contains(input);
        }
```

from FloatRange.cs
```
        public bool Contains(float value)
        {
            return value >= minimum && value <= maximum;
        }
```

from these code, if the bounds and the input values are *all exactly 5*, then it should have converted to `true`. 

from the livestream, the input value was from the step value of AngularTransformDrive. I believe it may not exactly be on 5 because of angle threshold and numeric errors. 

although we could try to include the floating point epsilon in the float range contains comparisons, the step value error could still be larger than epsilon depending on the threshold used

**Comment by thestonefox** [comment]
There's actually a test in the FloatRange that proves it works, so i think it may be something in the drive. I'm going to close this because its not a zinnia problem.
